export default {
  "blogs": [
    {
      "title": "So it Begins",
      "date": "04-04-2020",
      "blog": `With a Computer Science degree, one would believe it would be wise to jump straight into some area of Computer Science of relative complexity - Ruby on Rails; MongoDB with Python; Shopify theme development, etc.. - and try to garner some clientbase within a few weeks of focusing on this area. I mean, I have a degree.. Right? And I got a 1st, so surely that counts a lot insofar as employability is concerned? Can’t I just document all of the languages and architectures I’ve once been familiar with, state what I’m currently ‘proficient’ at, then hope that clientele will begin chomping away at that baited hook I’ve presented before them?

      Fortunately, I allowed my naivety to lead me only so far down this path, until my sense of anxiety forewarned me that continuing would only lead me to ruin.What do I mean by this? Well, for the past few weeks I have been focusing much time toward learning Ruby on Rails - yes, both of these in concurrency.I followed TheOdinProject’s structure of dabbling in some HTML, CSS, JavaScript, then sinking my teeth with greater intensity into Ruby, then Rails.Before jumping into Rails, however, I built a Kind Quotes app using HTML/ CSS / JS - a project of which I was incredibly enthusiastic about, where my casual daydreams would be superseded by ones pertaining to how to fix this bug, or how that new feature could be implemented.Yes, I was excited about this little project of mine, and I would program for hours each day, actually immersed in the personal project and looking forward to what feature I would next develop.But then I finished it; I decided it was time to ‘move onto what’s more important’...Namely: Ruby on Rails… Or so I thought.

      My deceitful desire to pursue Rails likely spawned from how I’m currently living with a freelance software developer who specializes in Shopify websites, using Ruby on Rails to manifest his client’s(well - paid) wishes.Coming to learn his hourly rate, how he has the potential to ignore would - be client requests for his work - a seed must have been planted within me that sprouted into a desire to follow this exact same path, for this mode of living is something I’ve never observed before in reality.Thus I speculated: I should follow this route.And it made sense, did it not ? If I were in need of help, well, I have a pro to give a hand, should I need it.And I would need it(and have needed it), for Rails is a complex architecture, especially with never having any prior experience with it.Yet my heart wasn’t in it.I have recently learned that I was likely pursuing this course of action for those tasty, alluring dollar signs.Money isn’t a massive motivator for me - yet it is something necessary in order to lead something of a fulfilling life, and the idea of freelancing is / can be a beautiful mode of living that, I believe, can be very liberating.

      The problem with Ruby on Rails is simply that it is too complex for me.I don’t know what type of projects I’d like to build with it.I don’t really know why I would want to do it, save for the prospect of money.And let’s touch on this prospect, shall we ? I saw this venture as something that would bring me money sooner, for I have a pro beside me who’s nearly always willing to dedicate a good amount of time to help me resolve any issues, and who has a lot of knowledge that pertains to finding jobs in that sector on websites like UpWork and Fiverr.Yet I regularly got frustrated at the mini - projects I was making, and was finding that, due to my lack of fundamental knowledge of the MVC framework and Rails in general, I was finding little - to - no enjoyment in my daily programming endeavours.Why Rails over other frameworks ? Why not become adept in React ? What about Flutter cross - platform app development ? None of these technologies enticed me, for I had no personal why to pursue then.Then I watched a YouTube video by a channel named ‘whatsdev’ (https://www.youtube.com/watch?v=sppSnBQVt0k) which helped reduce my anxiety by providing me with an answer that had recently been covered up by naive ambitions and skewed interests: Start with the fundamentals, and learn them so they become instinctual. I say this is something I innately ‘knew’, because I have ideas for different front-end applications that I’d like manifesting, but would not be able to achieve such a state if I dived into something complex like React or Rails. So I dropped the idea of pursuing rails - and all other complex technologies, for that matter - and have, as of yesterday, reverted to the absolute basics.`
    },
    {
      "title": "Away from Rails",
      "date": "05-05-2020",
      "blog": `There’s a tenet pertaining to job seeking that outlines that one should aim for something ‘higher,’ something more grandiose than a paycheck and a sense of existential stability. The term Ikigai is something worth investing some time into researching, and you may find some self-knowledge that will help your ambling down life’s unforetold path. While pursuing this Rails endeavour - with the intention to help others business dependent on Rails, such as Shopify stores - I felt a silent nausea that manifested only as a sense of dread - a dread of continuing to learn this framework and ‘progress’ toward something whose value I was become evermore uncertain of. Hence my day’s break a couple of days back. I wanted a reevaluation and, through gaining some distance from my daily myopia, I grasped the fact of an incongruity: I was pursuing something inauthentic, something not right for me at this point in my life. Thus I meditated on what could be that thing I’d like to pursue. A simple reflection on things I’ve recently enjoyed and have enjoyed throughout my Computer Science degree led me closer to the answer, until my Reason enabled me to grasp that which I now believe to be close enough to ‘The Answer’ that I’ve found a sense of inner-calm - the consequence, I believe, of authenticity.

      So I’ve spent the last 2 days coding away through a Udemy course on the basics of HTML and CSS - and I’m enjoying it. I have ideas reverberating about my stimulated mind - the blogging site wherein these blogs will someday lie ensconced; a Kindle Quotes application; a software development portfolio that I will use to showcase my developer skills; a website dedicated solely to my writing - and these thoughts are what I see as this ‘higher’ thing that is serving as the flames that lick against my back, ensuring that stasis is a state my being is unable to experience - or so I hope.
      
      This will all be slow going. As I stated in my last blog post, I have this degree, all of this experience - my ‘ego’ has stood unnoticed, impeding my ability to reason - and I thus thought I was ‘better’ than jumping into that which I learned 4 or so years ago. I don’t expect any monetary fruits to be born anytime soon - if my hope was for such, I’d likely be back learning Rails, trying to imposter myself into gigs that would make me feel like exactly that: an imposter. Instead, I’m (currently) enjoying plunging hours into these fundamentals, my ‘ego’ unheeded, positively anticipating the projects I will be able to create through the skills I will cultivate. Of course, I parenthesize the word ‘currently’, for I understand the transient ‘high’ one gets when pursuing something new and exciting. Keeping a positive distance from the short term when tedium becomes a part of my daily routine, will indeed help keep that flame licking my back at the fore of my mind.`
    },
    {
      "title": "Trudging Along",
      "date": "31-05-2020",
      "blog": `It’s been nearly 4 weeks since my last post.. What gives? Has my motivation, my discipline, been stunted? Have I lost my ‘passion’ for this blog? Trying to pinpoint the prime factor for an event (or lack thereof) isn’t something that can be done with any precision or certainty; there are always myriad reasons for any one seemingly simple thing’s being done or not done. All I can say is that I felt some silent resistance that manifested as an anxiety whenever I thought about coming to create another blog. Perhaps this is due to some perfectionism, or maybe due to fearing that, writing about what I’ve recently done, I will feel a sense of dread resulting from believing I’m not making sufficient progress in my endeavours. Nevertheless, here I am, nearly a month later, here to make another update.

      Today I have completed Brad Traversy’s Udemy course on HTML and CSS. This month of May has been rather stressful - I have dipped into something of a rut, slinking slowly into some habits I was beginning to curb - yet it is probably wise to feel at least some pride in not having succumbed to the pressure only I apply to myself and at having completed this course and learning plenty of HTML and CSS along the way. My way of working went as such: I would go through each lesson, then would attempt whatever Brad (the tutor) completed by myself; for any larger project, I would watch each lesson and then attempt it by myself - basically the same method as I used to go through the standalone lessons. After completing a larger project, I would sometimes start from scratch and attempt to create a more personalized version of the project, using as few pointers from my already-completed as possible.
      
      My next step is to build a portfolio website. I have bought a domain and will buy hosting as soon as my portfolio is completed. A comment on a YouTube video spoke about, when building a portfolio site, looking at other’s sites for inspiration, for it is not your job to be a UI/UX designer, but to be a developer, and thus, given you’re not copying the source code from various portfolios and are singly drawing inspiration therefrom, then there’s no issue. I aim to continue blogging (at greater frequency, of course), and after my portfolio is complete I believe I may begin looking on websites such as UpWork and Tutor to search for some form of work.`
    },
    {
      "title": "Dwindling Motivation",
      "date": "02-06-2020",
      "blog": `Yesterday I started developing my portfolio website. Perhaps my enthusiasm will develop as the site takes root and has its foundations complete, but as per yesterday I’ve not had a lot of excitement in the coding of this project. Likely it is due to feeling overwhelmed at the grandiosity of the project (albeit it isn’t oh-so grand, I know) and not knowing exactly where to start. I yesterday sat down and tried breaking the website down into pages, and then elements on each of those pages, and then I began coding. I reckon that, once I get into the swing of things, I’ll more positively anticipate my coding sessions.

      It’s interesting how we have a resistance toward things which thus impedes progress toward goals we deem valuable; is this resistance merely our ‘ego’, wiling away at our insecurities in order to keep us positioned right where we are, stagnating, lest we face the possibility of rejection and failure and the ego take the brunt of the pain? And with our beautifully rational minds that are often too irrational, we can misconstrue our ego’s pleads for comfort and thus exacerbate them: Something as trivial as simply beginning a coding project can evoke an anxiety disproportionately large.
      
      Visualization I hear is something that can be useful in shattering the ego’s deluded sense of self-protection, yet I prefer the simple act of getting some air: working out; going for a walk; simply sitting outside and informally meditating; journaling (or, in this case, blogging, for it is currently 06:30 and I’m writing this as a precursor to today’s work).`
    },
    {
      "title": "Hello, JavaScript!",
      "date": "04-06-2020",
      "blog": `Yesterday marked the first day of my JavaScript learning. Please note also that these blogs will either be written before or after the day’s work, and I hope that the chronology of the blog is implicit within the corresponding post. So, as I was saying, I started my JS learning yesterday by purchasing a Udemy course. For those interested, it’s the Modern JavaScript course by Colt Steele and Stephen Grider. For what reason did I purchase a course, when there’s an abundance of free resources online that would prove entirely sufficient for my becoming an advanced JS developer? Simply put, it’s due to how after having invested money into this product, I feel some sense of responsibility and/or obligation to carry out whatever the purchase entails.

      The ironic thing about freedom is that we feel trapped with too much of it. If there were certain constraints that allowed me only to select one of two JS courses on Udemy, I can almost guarantee that I’d have had an easier time selecting my purchase than was my experience yesterday, which entailed a scraping of Reddit and Quora to find which one was ‘best’. And of course I found only a multitude of conflicting opinions on how this instructor was better than that one, but then how that instructor taught things that this one missed out… Our rational mind can sometimes be burdensome when given a task of which we place too great a sense of importance. I eventually made my decision based on: the number of hours the course consists of; the enticing projects entailed; the reputation of both instructors.
      
      I continued with my portfolio yesterday, beginning and getting some distance on my project showcase section, and then beginning the ‘Exercises’ section, where I hope to showcase all the small exercises I have completed through these Udemy courses. I spent some time with a friend brainstorming different forms of presenting these exercises, for I desire a very minimalistic theme for the website yet want to present much information in this section. After storming the brain for some time I vaguely decided upon the idea of having three buttons - one for each HTML, CSS, and JS - that each, upon click, popup an overlay/modal that presents to the user a plethora of exercises pertaining to that language. Today I intend to carry out this intention to some degree by at least getting the buttons on the page, and then I’ll likely move on to the Blog section of my portfolio, wherein will lie these posts (and likely the one you’re currently reading). Afterward, I’ll move onto learning some JS from the aforementioned course.`
    },
    {
      "title": "Who am I?",
      "date": "06-06-2020",
      "blog": `It may be of your interest to learn about my current situation, to give some context to these blogs and, well, establish some ‘virtual, one-way connection’ between you and I. So, I’m currently living in a hostel in Melbourne, Australia (in a suburb called, Brunswick, if you’re so interested). I came over here with little intention other than to explore different modes of work and attempt to establish an ‘empire’. I’ll try and keep this somewhat brief, so please bare with me…

      I have a first class honors degree in Computer Science, yet for the latter half of my degree I greatly detest CompSci and, after finishing my degree, I was dead-set on straying as far from the industry as possible for the indefinite future (I wasn’t naive enough to state that I’d never touch the industry again, but that I needed a very long break from it). I achieved such a classification due to wanting to prove to myself that I could do it, not because I enjoyed what I was doing. And thus, wanting some independence, a new environment, and an abundance of potential imbued within my surroundings, I booked my flight over here. I figured I’d try working in various industries over here just to learn more about myself - my likes/dislikes, etc. - but things didn’t go ‘as plan’ (insofar as there was anything of a plan). I’m cohabiting with a total of around 10 others, and one of those is a freelance software developer. He’s been my primary source of inspiration for this road I’m now travelling down.
      
      I first realized that my ‘plan’ was incoherent with my life situation when I lost a sales job on my very first shift. Oh, I hadn’t yet the chance to exercise any sales skills (or lack thereof) that could warrant my immediate termination; no, rather, COVID had called off the shift, and all shifts thereafter. And thus I entertained the notion of freelancing, and I began learning Ruby on Rails through The Odin Project with the hope of working on UpWork. Why Ruby on Rails? Well, simply because my freelancing housemate purported the framework’s greatness. This meant there was a lack of freethinking on my part or, moreover, a lack of considering whether I could be interested enough in the technology to allow for a sustained intention to keep learning and eventually work with the technology. I saw too shallowly: I concluded that, since I had told myself that nothing in CompSci was of much interest, the technology I decided upon mattered little and thus, because I have available someone with vested interest and skill in Ruby on Rails, I may as well set my sails toward mastering this technology. This backfired for, after spending a couple of weeks playing with the framework, I quickly grew tired and realized I was in over my head. I backtracked and realized that, through creating a Kindle Quotes app as an exercise to learn some HTML/CSS/JS, I enjoyed front-end.
      
      And here I am now. Hopefully this has provided something of a context for my current life situation. I would, however, like to quickly go over the word ‘empire’ I employed earlier when speaking about how I wanted to build one when coming over to Melbourne. I simply mean a personal empire, which entails my: relationships (both romantic and platonic); means of income; living situation; diet, exercise, and other daily habits. Basically, I wanted to establish myself and beginning living a life greatly in line with my values, and wanted to further understand myself and thus my values, constantly realigning my life with what I would be learning about myself. I cannot say I’m doing a fantastic job of this at present, for, if I had greater autonomy, I wouldn’t be living in a hostel. Yet I’m making pretty good of a pretty (objectively, from a worldly, human standpoint) poor situation (and yes, I’m referencing COVID here). I have about 11-12 weeks left of sustaining myself here in this hostel until I’m completely - savings and all - dry of cash; and so, as one can imagine, facing dire straits has caused for a decent motivation toward becoming self-employed.`
    },
    {
      "title": "Happy 40th Birthday!",
      "date": "12-06-2020",
      "blog": `Today marks the fortieth day of my front-end development journey. I’m currently going through a JavaScript Udemy course, and am investing a good chunk of time into it each day, finding a significant amount of enjoyment during these hours of investment - that is, a good amount of enjoyment considering that I’m studying. Sometimes it’s easy for me to become myopic in regard to my progress with this whole endeavour: I will often become struck by a sense of stagnation, that I’m not moving forward fast enough, that financial freedom (and thus, to some extent, existential freedom) is something unachievable and is something I won’t be able to reach lest I take the ‘safe’ route of getting a standard, full-time job and thus do what’s ‘expected’ of me.

      Envisioning a self that is able to work if, when, and where he pleases, and is able to work only a few hours a day to sustain the lifestyle he desires, is a reality that I’ve pedestalized as fantasy, and my aim for the next 40 days is to make a sustainable effort at taking this fantasy from the pedestal and work to tame such a beast so I’m a step closer to integrating myself into such a fruitful lifestyle.
      
      I feel a resistance toward continuing working on my portfolio site: It’s so much easier to just work through a course, being guided by the reassuring voice of the instructor. Much more anxiety is found when jumping into the unknown, into that which promises no results other than pangs of frustration. Yet this latter road is surely the more prolific one, and is one I must amble down sooner rather than later. Thus my goal over the next week is to, yes, continue working through this JavaScript course, but concurrently work on my website so as to create something that I can start becoming proud of.`
    },
    {
      "title": "Persistent Disquiet",
      "date": "23-06-2020",
      "blog": `One of the main sources of disquiet in this endeavour is the uncertainty contained within. Not having a definitive time when I will begin earning money is certainly cause for anxiety; perhaps this isn’t true for all but, given my current situation, it certainly appears to be the case for myself. Thus, I yesterday went and planned out all that I ‘need’ to do before I start applying for contracts. This lists consists of: completing the Udemy JavaScript course; completing at least 5 projects that use JS/HTML/CSS; complete my portfolio website. Fortunately, I have a couple of project ideas that are entirely personal and aren’t simply something that an online tutor prescribes for me. One of these ideas I am very close to completing, and I feel a tinge of genuine excitement for beginning to work on the second idea. These spurts of excitement are what I hope to feel (at least to a minor extent) when I begin working. Perhaps this anticipation, this hope, is entirely naive, yet I do hope that I do in part feel a sense of joy when actually working for clientele.

      Since my last update, I have primarily been trudging away, working through this Udemy course. After working on it for a good few days, I grew fatigued by it and uninterested. This brought about a good deal of mental unrest due to feeling that hadn’t been, and thus wasn’t, getting anywhere, and thus I ended up planning out exactly what I need to complete before I start applying for jobs. I believe this unrest sourced from how, when completing a course, although you may be learning a good deal, you’re not building content that brings that sense of fulfilment that’s required to really feel that you’re making progress. This should explain why I today aim to work only my portfolio website and how I yesterday worked on a personal project. My intention for the next week is to finish this first personal app, develop my website somewhat so that these blog posts are neatly presented on it, and begin my second personal project.`
    },
    {
      "title": "Back in Action",
      "date": "25-10-2020",
      "blog": `After a 3-month hiatus, I’m back programming. What prompted this break? Was I taking respite from something I wasn’t enjoying? Well, yes, I was distancing myself from something that became unpleasant and stressful. Is this because programming simply “isn’t for me”? No, I do not believe this to be the reason - although, throughout this programming lacuna, I did certainly entertain the idea that I just wasn’t compatible with programming. But then I pondered deeper, and arrived at an uncomfortable, yet potentially liberating answer: I was the problem.
      I questioned what I wanted for the future and contemplated multiple paths - not one of which included a 9-5. Further, I conceded to (what I consider) the fact that freelance software/website development is the only truly feasible short-/mid-term solution for my personal needs. But, I told myself, I cannot force myself to do something that simply isn’t for me. Thus I questioned more, contemplated deeper, and learned that, indeed, the problem lies within me, not between myself and programming. To put it simply, I expected too much of myself, pushing to work 6-7 hours a day, with the pressure of needing to begin making an income within 2-3 months, lest I be forced to fly back to England, away from the impending Australian summer. I didn’t break down tasks, and saw no fruit being born from my labours: I was working, sure, but I considered that which I produced to be of little-to-no value, for I simply couldn’t fathom this whole pursuit cultivating an ounce of success.
      Yet here I am again, writing to you, programming. Why? For me, presently, freelance software development is the only feasible means of attaining any semblance of financial freedom within the next year or two; and, more importantly, I’ve learned that the problem isn’t with programming, but with what I expect of myself, the pressures I pin onto myself, not appreciating that which I’ve achieved. It’s also worth mentioning that I’ve had a full-time job for the past 3 months, which would make one question whether I’m putting too much stress on myself, trying to work a full-time, physical job, whilst concurrently expecting myself to program. However, this large constraint is actually enabling me to program with fewer neurotic side-effects, because, rather than having empty days wherein I expect myself to incessantly program, I now have to try and sneak an hour of programming in before work, and a bit more at weekends. In addition, I don’t have the pressure to “code or die”, because I have an income which subtracts the servere time constraint that was otherwise debilitating my efforts.
      I’m currently chipping away at my portfolio, and look forward to starting other projects. Rather than giving myself a mere three months to achieve this goal, I’ve set something like a twelve month distance to complete the task, which is far enough into the future to restrict the pressure I feel, whilst being close enough to encourage me to invest a decent number of hours into working each week. One of my biggest challenges, seemingly ironically, is to ensure I don’t work too much, because otherwise I will stop enjoying this process and my work will be tainted by compulsion, as opposed to passion and curiosity.`
    }
  ]
}